https://project-books-2.herokuapp.com/books

###
https://project-books-2.herokuapp.com/books/3


###

https://project-books-2.herokuapp.com/books/0/save?categoryId=2&name=Война и Мир&author=Н.Н.Толстой&price=550


 

###

https://project-books-2.herokuapp.com/books/categories/2

###

 https://project-books-2.herokuapp.com/books/8/save?categoryId=2&name=Война и Мир&author=Л.Н.Толстой&price=550

###


https://project-books-2.herokuapp.com/books/8/remove

###

 https://project-books-2.herokuapp.com/books/search?name=Мы&author=Е.И.Замятин

 ###







